name: Lens & index validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./validator
    steps:
    # Checkout source code
    - uses: actions/checkout@v3
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: actions/checkout@v3
      if: github.event_name == 'push'
      with:
        fetch-depth: 0
    # Setup rust toolchain
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
    # Should help bring down build times
    - uses: Swatinem/rust-cache@v1
      with:
        key: "1" # increment this to bust the cache if needed
    - name: Run validator & generate index file
      run: cargo run
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update index file
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: '[Automated] Update index file'
        labels: automated pr
