name: Lens & index validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./validator
    steps:
    # Checkout source code
    - uses: actions/checkout@v3
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: actions/checkout@v3
      if: github.event_name == 'push'
      with:
        fetch-depth: 0
    # Setup rust toolchain
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
    # Should help bring down build times
    - uses: Swatinem/rust-cache@v1
      with:
        key: "1" # increment this to bust the cache if needed
    - name: Run validator & generate index file
      run: cargo run
    - name: Commit new index file
      run: |
        git config --global user.name 'Andrew Huynh'
        git config --global user.email 'a5huynh@users.noreply.github.com'
        git commit -am "new index file generated"
        git push
